const UINT32_MAX = 0xffffffff;

/**
 * Repair small RIFF/WAVE files produced as streaming responses.
 *
 * Some TTS services cannot know the final byte length when they emit the WAV
 * header, so they leave RIFF and data chunk sizes at 0xffffffff. The PCM
 * payload is valid, but strict readers report a corrupt packet at end-of-file.
 * This function changes container metadata only; audio samples are untouched.
 */
export function normalizeWavBuffer(input) {
  if (!Buffer.isBuffer(input)) {
    throw new TypeError("input must be a Buffer");
  }

  if (
    input.length < 12
    || input.toString("ascii", 0, 4) !== "RIFF"
    || input.toString("ascii", 8, 12) !== "WAVE"
  ) {
    return {
      buffer: input,
      recognized: false,
      changed: false,
      repairs: [],
    };
  }

  if (input.length - 8 > UINT32_MAX) {
    throw new RangeError("RIFF/WAVE normalization does not support files larger than 4 GiB");
  }

  const output = Buffer.from(input);
  const repairs = [];
  const expectedRiffSize = output.length - 8;
  const declaredRiffSize = output.readUInt32LE(4);

  if (declaredRiffSize !== expectedRiffSize) {
    output.writeUInt32LE(expectedRiffSize, 4);
    repairs.push({
      field: "riff_chunk_size",
      from: declaredRiffSize,
      to: expectedRiffSize,
    });
  }

  const dataChunk = findDataChunk(output);
  if (dataChunk) {
    const availableBytes = output.length - dataChunk.payloadOffset;
    if (availableBytes > UINT32_MAX) {
      throw new RangeError("WAV data chunk exceeds the RIFF 32-bit size limit");
    }

    // A streaming sentinel or an impossible declared size means that the data
    // chunk runs to EOF. PCM generated by the current Gradium integration is
    // block-aligned, so no ambiguous trailing pad byte is expected.
    if (
      dataChunk.declaredSize === UINT32_MAX
      || dataChunk.declaredSize > availableBytes
    ) {
      output.writeUInt32LE(availableBytes, dataChunk.headerOffset + 4);
      repairs.push({
        field: "data_chunk_size",
        from: dataChunk.declaredSize,
        to: availableBytes,
      });
    }
  }

  return {
    buffer: repairs.length > 0 ? output : input,
    recognized: true,
    changed: repairs.length > 0,
    repairs,
  };
}

function findDataChunk(buffer) {
  let offset = 12;

  while (offset + 8 <= buffer.length) {
    const chunkId = buffer.toString("ascii", offset, offset + 4);
    const declaredSize = buffer.readUInt32LE(offset + 4);
    const payloadOffset = offset + 8;

    if (chunkId === "data") {
      return {
        headerOffset: offset,
        payloadOffset,
        declaredSize,
      };
    }

    const paddedSize = declaredSize + (declaredSize % 2);
    const nextOffset = payloadOffset + paddedSize;
    if (nextOffset <= offset || nextOffset > buffer.length) break;
    offset = nextOffset;
  }

  // Defensive fallback for unusual ancillary chunks with an invalid declared
  // size before the data chunk. Restrict candidates to even byte boundaries,
  // as RIFF chunks are word-aligned.
  for (let candidate = 12; candidate + 8 <= buffer.length; candidate += 2) {
    if (buffer.toString("ascii", candidate, candidate + 4) === "data") {
      return {
        headerOffset: candidate,
        payloadOffset: candidate + 8,
        declaredSize: buffer.readUInt32LE(candidate + 4),
      };
    }
  }

  return null;
}
